// Menu data for 木漏れ日カフェ
// Prices in JPY.

export const pastries = [
  {
    id: "tiramisu",
    nameJp: "ティラミス",
    nameEn: "Tiramisu",
    price: 680,
    desc: "マスカルポーネとエスプレッソの重なり。ココアの粉雪。",
    batch: "本日 14:00",
    accent: "espresso",
    image: "https://media.base44.com/images/public/6a7c0fbc3673521b41e904a4/e6dd2daae_generated_d4435437.png",
  },
  {
    id: "croissant",
    nameJp: "バタークロワッサン",
    nameEn: "Butter Croissant",
    price: 420,
    desc: "層の果てまで折り重ねた、北海道発酵バターの香り。",
    batch: "本日 11:00",
    accent: "gold",
    image: "https://media.base44.com/images/public/6a7c0fbc3673521b41e904a4/4434f53aa_generated_7fd5de47.png",
  },
  {
    id: "cheesecake",
    nameJp: "チーズケーキ",
    nameEn: "Cheesecake",
    price: 560,
    desc: "しっとり、ふわり。焼き込みの時間がつくる濃厚な口溶け。",
    batch: "本日 15:30",
    accent: "cream",
    image: "https://media.base44.com/images/public/6a7c0fbc3673521b41e904a4/6cd979e95_generated_9337bd8f.png",
  },
  {
    id: "millefeuille",
    nameJp: "ミルフィーユ",
    nameEn: "Mille-feuille",
    price: 720,
    desc: "三枚の薄い生地と二層のクリーム。崩れるほどに美しい。",
    batch: "本日 13:00",
    accent: "vanilla",
    image: "https://media.base44.com/images/public/6a7c0fbc3673521b41e904a4/3575629be_generated_52a9eac0.png",
  },
];

export const drinks = [
  {
    id: "americano",
    nameJp: "アメリカーノ",
    nameEn: "Americano",
    price: 480,
    profile: { sweetness: 1, acidity: 4, body: 3 },
    note: "深煎りの輪郭を、お湯でくっきりと。",
  },
  {
    id: "cafelatte",
    nameJp: "カフェラテ",
    nameEn: "Café Latte",
    price: 540,
    profile: { sweetness: 2, acidity: 2, body: 4 },
    note: "白磁に浮かぶ、木漏れ日のような模様。",
  },
  {
    id: "matchalatte",
    nameJp: "抹茶ラテ",
    nameEn: "Matcha Latte",
    price: 620,
    profile: { sweetness: 2, acidity: 3, body: 4 },
    note: "宇治の石臼挽き。青葉の余韻。",
  },
  {
    id: "cappuccino",
    nameJp: "カプチーノ",
    nameEn: "Cappuccino",
    price: 520,
    profile: { sweetness: 1, acidity: 3, body: 4 },
    note: "細かい泡の天蓋。修道士の色。",
  },
  {
    id: "espresso",
    nameJp: "エスプレッソ",
    nameEn: "Espresso",
    price: 380,
    profile: { sweetness: 1, acidity: 4, body: 5 },
    note: "一瞬の濃縮。三十秒で消える温度。",
  },
  {
    id: "mocha",
    nameJp: "モカ",
    nameEn: "Mocha",
    price: 580,
    profile: { sweetness: 4, acidity: 2, body: 4 },
    note: "珈琲とカカオ、二つの褐色の融和。",
  },
  {
    id: "honeylatte",
    nameJp: "ハニーラテ",
    nameEn: "Honey Latte",
    price: 600,
    profile: { sweetness: 5, acidity: 1, body: 3 },
    note: "蜂の巣から、ゆっくりと垂れる甘み。",
  },
  {
    id: "coldbrew",
    nameJp: "水出し珈琲",
    nameEn: "Cold Brew",
    price: 560,
    profile: { sweetness: 2, acidity: 2, body: 4 },
    note: "八時間かけて落ちた、冷たい旋律。",
  },
  {
    id: "earlgrey",
    nameJp: "アールグレイ",
    nameEn: "Earl Grey",
    price: 460,
    profile: { sweetness: 1, acidity: 3, body: 2 },
    note: "ベルガモットの香りが先に立つ。",
  },
  {
    id: "cocoa",
    nameJp: "ホットココア",
    nameEn: "Hot Cocoa",
    price: 540,
    profile: { sweetness: 5, acidity: 1, body: 4 },
    note: "焦がさず、ゆっくり溶かした巧克力。",
  },
];